server:
  port: 8081
  servlet:
    contextPath: /
  maxHttpHeaderSize: 4048576
spring:
  application:
    name: center
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        maxActive: 600
        maxWait: 1000s
        maxIdle: 300
    timeout: 10000s
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    instanceId: ${eureka.instance.hostname}:${server.port}
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/