server:
  port: 8081
  servlet:
    context-path: /
  max-http-header-size: 4048576
logging:
  config: classpath:logback.xml
spring:
  application:
    name: monitor
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 600
        max-wait: 1000s
        max-idle: 300
    timeout: 10000s
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/