server:
  port: 8080
  servlet:
    context-path: /
logging:
  config: classpath:logback.xml
spring:
  application:
    name: server
  profiles:
    active: server
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 600
        max-wait: 1000s
        max-idle: 300
    timeout: 10000s
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  server:
    enable-self-preservation: false