server:
  port: 8080
  servlet:
    context-path: /
  max-http-header-size: 4048576
logging:
  config: classpath:logback.xml
spring:
  application:
    name: system
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 600
        max-wait: 1000s
        max-idle: 300
    timeout: 10000s
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
zuul:
  routes:
    system: /system/**
    monitor: /monitor/**
    quartz: /quartz/**
    crawler: /crawler/**
  retryable: true