server:
  port: 8083
  servlet:
    contextPath: /
  maxHttpHeaderSize: 4048576
logging:
  config: classpath:logback.xml
spring:
  application:
    name: crawler
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/titan?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        maxActive: 600
        maxWait: 1000s
        maxIdle: 300
    timeout: 10000s
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
